#!/usr/bin/python3
# -----------------------------------------------------------------------
# A small python script to scrape the public pastebin archive.
# Copyright (C) 2019  Mili
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------
import sys
import base64
from os import remove, system
'''
This is used for decoding base64 encoded gzips and zips

like isMalicious, this will likely be integrated into the program soon
'''
def main(encodedfile):
    with open(encodedfile, 'r') as b64file:
        data = base64.b64decode(b64file.read())
        newfilename = (encodedfile.split(".")[0]).split("_")[1]

        if encodedfile.startswith("H4sI"):
            with open(f"{newfilename}.gz", "wb") as gzfile:
                gzfile.write(data)
                remove(encodedfile)
                try:
                    system(f"gunzip -d {newfilename}.gz")
                    filetype = system(f"file {newfilename}")
                    print(filetype)
                    if "executable" and "windows" in filetype:
                        system(f"mv {newfilename} {newfilename}.exe")
                    elif "ASCII" in filetype:
                        system(f"mv {newfilename} {newfilename}.txt")
                except Exception as e:
                    print(f"{e}")
        elif encodedfile.startswith("UEs"):
            with open (f"{newfilename}.zip", "wb") as zipfile:
                zipfile.write(data)
                remove(encodedfile)

if __name__ == "__main__":
    try:
        main(sys.argv[1])
    except IndexError:
        print(f"Usage: {sys.argv[0]} <filename>")
