#!/usr/bin/python3
# -----------------------------------------------------------------------
# A small python script to scrape the public pastebin archive.
# Copyright (C) 2019  Mili
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------
import os
"""
This a development utility for detecting errors in YARA matching
"""
def main():
    blacklisted_terms = ["EXTINF:", "EXTM3U", "chegg", "bukkit", "minecraft", "serfish",
                         "Technic Launcher is starting", "[Server Thread/WARN]", "SimC Addon",
                         "M3U", "fortnite"]
    for file in [f for f in os.listdir(os.getcwd()) if os.path.isfile(f)]:
        with open(file, 'r') as f:
            if any(term.lower() in f.read().lower() for term in blacklisted_terms):
                print(f"Blacklisted terms in {file}. YARA error likely.")
if __name__ == '__main__':
    main()
